In [7]:
import unittest
import numpy as np
import raster_scan

In [14]:
# y is same format as our input videos
y = np.arange(18).reshape((3, 3, 2))
y = np.swapaxes(y, 0, 2)
y = np.swapaxes(y, 0, 1)

# z is now what we want as output if y was our input
z = np.arange(18).reshape((3, 6))

In [15]:
np.testing.assert_array_equal(raster_scan.raster_scan(y), z)

In [16]:
# Using the print method to confirm I did the unit test right
print(rs.raster_scan(y))
print(z)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [17]:
# Testing different dimensions
a = np.arange(24).reshape((4, 2, 3))
a = np.swapaxes(a, 0, 2)
a = np.swapaxes(a, 0, 1)

b = np.arange(24).reshape((4, 6))

np.testing.assert_array_equal(raster_scan.raster_scan(a), b)

In [18]:
c = np.arange(8).reshape((2, 2, 2))
c = np.swapaxes(c, 0, 2)
c = np.swapaxes(c, 0, 1)

d = np.arange(8).reshape((2, 4))

np.testing.assert_array_equal(raster_scan.raster_scan(c), d)

In [19]:
# Testing our theoretical 100 frame, 120x120 video
e = np.arange(1440000).reshape((100, 120, 120))
e = np.swapaxes(e, 0, 2)
e = np.swapaxes(e, 0, 1)

f = np.arange(1440000).reshape((100, 14400))

np.testing.assert_array_equal(raster_scan.raster_scan(e), f)