In [15]:
import unittest
import numpy as np
import raster_scan as rs

In [24]:
# this is the format I found for unit tests online, but I think assertEqual doesn't work for np arrays maybe
class TestRasterScan(unittest.TestCase):

    def test_rasterscan(self):
        y = np.arange(18).reshape((3, 3, 2))
        y = np.swapaxes(y, 0, 2)
        y = np.swapaxes(y, 0, 1)
        z = np.arange(18).reshape((3, 6))
        
        self.assertEqual(rs.raster_scan(y), z)
        
if __name__ == '__main__':
    unittest.main()

E
ERROR: /Users/BrittanyDorsey/Library/Jupyter/runtime/kernel-bd50e187-2ba6-4ad5-b67e-99572923303b (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute '/Users/BrittanyDorsey/Library/Jupyter/runtime/kernel-bd50e187-2ba6-4ad5-b67e-99572923303b'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


SystemExit: True

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [28]:
# Using the print method to confirm I did the unit test right
print(rs.raster_scan(y))
print(z)

[[ 0  6 12  2  8 14]
 [ 4 10 16  1  7 13]
 [ 3  9 15  5 11 17]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [21]:
# This may be the right format for unit tests for np arrays
# It results in the same mismatch as the printing method above
np.testing.assert_array_equal(rs.raster_scan(y), z)

AssertionError: 
Arrays are not equal

(mismatch 88.88888888888889%)
 x: array([[ 0,  6, 12,  2,  8, 14],
       [ 4, 10, 16,  1,  7, 13],
       [ 3,  9, 15,  5, 11, 17]])
 y: array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])