In [22]:
import numpy as np
import raster_scan
import unittest

In [27]:
class TestRasterScan(unittest.TestCase):

    def test_rasterscan(self):
        y = np.arange(18).reshape((3, 3, 2))
        y = np.swapaxes(y, 0, 2)
        y = np.swapaxes(y, 0, 1) # y is same format as our input videos
        z = np.arange(18).reshape((3, 6)) # z is now what we want as output if y was our input
        
        np.testing.assert_array_equal(raster_scan.raster_scan(y), z)


In [28]:
if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)    


F
FAIL: test_rasterscan (__main__.TestRasterScan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-27-e6847a9c0ba4>", line 9, in test_rasterscan
    np.testing.assert_array_equal(raster_scan.raster_scan(y), z)
  File "/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 66.66666666666666%)
 x: array([[ 0,  1,  6,  7, 12, 13],
       [ 2,  3,  8,  9, 14, 15],
       [ 4,  5, 10, 11, 16, 17]])
 y: array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)


In [15]:
np.testing.assert_array_equal(raster_scan.raster_scan(y), z)

In [11]:
y = np.arange(18).reshape((3, 3, 2))
y = np.swapaxes(y, 0, 2)
y = np.swapaxes(y, 0, 1) # y is same format as our input videos
z = np.arange(18).reshape((3, 6)) # z is now what we want as output if y was our input
# Using the print method to confirm I did the unit test right
print(raster_scan.raster_scan(y))
print(z)

[[ 0  1  6  7 12 13]
 [ 2  3  8  9 14 15]
 [ 4  5 10 11 16 17]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [36]:
k = y = np.arange(18).reshape((3, 3, 2))
k

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [37]:
y = np.swapaxes(y, 0, 1)
y

array([[[ 0,  1],
        [ 6,  7],
        [12, 13]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15]],

       [[ 4,  5],
        [10, 11],
        [16, 17]]])

In [38]:
z = np.arange(18).reshape((3, 6)) # z is now what we want as output if y was our input
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [39]:
video = np.swapaxes(y, 1, 2) # Now is (F, W, H)
video

array([[[ 0,  6, 12],
        [ 1,  7, 13]],

       [[ 2,  8, 14],
        [ 3,  9, 15]],

       [[ 4, 10, 16],
        [ 5, 11, 17]]])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [40]:
    # Reshape.
    n_pixels = video.shape[1] * video.shape[2]
    n_frames = video.shape[0]
    print(n_pixels, n_frames)

6 3


In [41]:
    matrix = video.reshape((n_frames, n_pixels))
    matrix

array([[ 0,  6, 12,  1,  7, 13],
       [ 2,  8, 14,  3,  9, 15],
       [ 4, 10, 16,  5, 11, 17]])